spring.application.name=Majesty-BIT
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/majesty_realm
spring.datasource.username=majesty_user
spring.datasource.password=majesty_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true